### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by vassilit** [nohal/imgkap#10]
Hello,

I find this tool useful — I thank you for it — and I would like to make and eventually maintain a package for Arch Linux.
Do you mind ? Is this software GPLv2 ?

**Comment by nohal** [comment]
No, I certainly don't mind and don't plan to do it myself in any foreseeable future. The license is "GPLv3 or later" -  https://github.com/nohal/imgkap/blob/master/imgkap.c#L1-L27
