### ISSUE TITLE
License of imgkap?

### ISSUE THREAD

**Issue by philliphoff** [nohal/imgkap#11]
What's the license associated with this repo?

**Comment by rgleason** [comment]
Readme says
This repository is a Github clone of the original code created by M'dJ in 2011 and maintained by Pavel Kalian

Find Mdj in 2011 and see

**Comment by rgleason** [comment]
https://www.google.com/search?client=firefox-b-1-d&q=imgkap+M%27dJ+

https://www.google.com/search?client=firefox-b-1-d&q=imgkap+M%27dJ+

**Comment by rgleason** [comment]
This source is free writen by M'dJ at 09/04/2011 * Use open ...
www.dacust.com › inlandwaters › imgkap › imgkap
This source is free writen by M'dJ at 09/04/2011 * Use open source FreeImage and gnu gcc * Thank to freeimage, libsb and opencpn * * imgkap.c - Convert kap ...
You've visited this page 4 times. Last visit: 3/24/21

**Comment by nohal** [comment]
When I tried to agree on a license with the original author, all he said before disappearing forever was "It is free, I don't care". Which I personally translate like public domain, but I'm certainly not a lawyer and have zero interest in becoming one.

**Comment by nohal** [comment]
Now that I actually remembered, the ultimate result of that discussion was GPL3+ (https://github.com/nohal/imgkap/commit/bc5b99ad0f6cee3b39e5bbac189bc703590f4a7d)

**Comment by philliphoff** [comment]
@nohal Thanks, that's good to know.
